### ISSUE TITLE
Argon2 authentication `Bun.password`

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/substreams-sink-clickhouse#51]
Replacement for AuthKey logic using `Bun.password`

- [ ] ~add `MNEMONIC` to config (BIP39 - Mnemonic Code Words) to config (used to replace `AUTH_KEY`)~
- [x] Secret password can remain `AUTH_KEY`
  > https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki
- [x] implement `argon2` authentication (ex: `Bun.password`) 
  > https://bun.sh/guides/util/hash-a-password
- [x] add tests
- [x] update documentation as feature

```ts
// https://bun.sh/guides/util/hash-a-password
import { config } from "../config.js";
import { InvalidRequest, NoAuthorization, Unauthorized, getBearer } from "./bearerAuth.js";

export function beforeHandle(request: Request) {
    if ( !config.AUTH_KEY ) return;
    const bearer = getBearer(request);
    if (!bearer) return NoAuthorization;

    try {
        const verify = Bun.password.verifySync(config.AUTH_KEY, bearer);
        if ( !verify ) return Unauthorized;
    } catch (e) {
        return InvalidRequest;
    }
}
```

## Reference

Argon2 is one of the safest cryptographic algorithm for password encryption
https://www.boldare.com/blog/how-to-improve-user-password-security-with-argon2/

StreamingFast (previously EOS Canada) had used this for their command line wallet
https://github.com/eoscanada/eosc

**Comment by JulienR1** [comment]
Implemented in #58
