### ISSUE TITLE
`module_hashes` needs to support multiple chains

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/substreams-sink-clickhouse#54]
`ReplacingMergeTree` causes modules from the different chains to be merged into one entity.

https://github.com/pinax-network/substreams-sink-clickhouse/blob/main/src/clickhouse/tables/module_hashes.sql

<img width="827" alt="image" src="https://github.com/pinax-network/substreams-sink-clickhouse/assets/550895/dc4ded3d-ca59-43e1-8720-db83c7d5eb6d">

Result expects to have 3 chains

I think, would do the trick?

```sql
ORDER BY (module_hash, chain);
```

**Comment by JulienR1** [comment]
Sorting key updated
