### ISSUE TITLE
Load data from SQLite directly into ClickHouse

### ISSUE THREAD

**Issue by JulienR1** [pinax-network/substreams-sink-clickhouse#74]
Remove the "`SELECT` from SQLite -> `INSERT` into ClickHouse" step.

Replace it with a `INSERT FROM SQLite` step directly into ClickHouse.

This could be harder to implement because of location constraints on `.sqlite` enforced by ClickHouse and Railway.

**Comment by DenisCarriere** [comment]
implemented
