### ISSUE TITLE
Extend `module_hashes` to include last values

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/substreams-sink-clickhouse#88]
- [x] Extend modules to include last values for:
  - `cursor`
  - `block_number`
  - `block_id`
- [x] drop `cursors` table

![image](https://github.com/pinax-network/substreams-sink-clickhouse/assets/550895/6c6e6175-88fa-4ad1-a1c5-0ec31cbd8271)

**Comment by JulienR1** [comment]
PR: #92
