### ISSUE TITLE
Add MaterialViews or Skipping Indexes

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/substreams-sink-clickhouse#90]
Look into those MaterialView or Skipping Indexes

## Research
- https://clickhouse.com/docs/en/optimize/sparse-primary-indexes#option-2-materialized-views
- https://clickhouse.com/docs/en/optimize/skipping-indexes

## Testing with
 
All should return by scanning ~40-50K rows

```sql
SELECT * from timestamp_index WHERE timestamp > '2021-09-26 00:00:00' ORDER BY timestamp LIMIT 10

SELECT * from block_number_index WHERE block_number > 13300000 ORDER BY block_number LIMIT 10

SELECT * from blocks WHERE block_id = 'adc51915c11ca5beaad9f220f36b63a70e5545f64d297445749d228297cbb629'
```

## Example

```sql
CREATE MATERIALIZED VIEW mv_blocks_block_number
ENGINE = MergeTree()
ORDER BY block_number
POPULATE
AS SELECT * FROM blocks;
```

**Comment by JulienR1** [comment]
Default indexes have been added. The rest can be added by the user when creating a schema if needed.
